checks:
    php: true
filter: {  }
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                concatenation: true
