<?php

namespace TheSportsDb\Test\Entity;

use TheSportsDb\Entity\EntityManagerInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-08 at 10:34:14.
 */
class EntityManagerConsumerTraitTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var object
   */
  protected $entityManagerConsumer;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->entityManagerConsumer = $this->getObjectForTrait('\\TheSportsDb\\Entity\\EntityManagerConsumerTrait');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    $this->entityManagerConsumer = NULL;
  }

  /**
   * @covers TheSportsDb\Entity\EntityManagerConsumerTrait::setEntityManager
   */
  public function testSetEntityManager() {
    $manager = $this->getMockBuilder(EntityManagerInterface::class)->getMock();
    // Once should be fine.
    $this->entityManagerConsumer->setEntityManager($manager);

    // Manager already set == Exception.
    $this->expectException(\Exception::class);
    $this->expectExceptionMessage('Entity manager already set.');
    $this->entityManagerConsumer->setEntityManager($manager);

  }

}
