<?php

namespace TheSportsDb\Test\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 11:46:08.
 */
class EventTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Event';

  /**
   * @covers TheSportsDb\Entity\Event::getId
   * @covers TheSportsDb\Entity\Event::getName
   * @covers TheSportsDb\Entity\Event::getLeague
   * @covers TheSportsDb\Entity\Event::getFilename
   * @covers TheSportsDb\Entity\Event::getSeason
   * @covers TheSportsDb\Entity\Event::getDescription
   * @covers TheSportsDb\Entity\Event::getHomeScore
   * @covers TheSportsDb\Entity\Event::getRound
   * @covers TheSportsDb\Entity\Event::getAwayScore
   * @covers TheSportsDb\Entity\Event::getSpecators
   * @covers TheSportsDb\Entity\Event::getHomeGoalDetails
   * @covers TheSportsDb\Entity\Event::getHomeRedCards
   * @covers TheSportsDb\Entity\Event::getHomeYellowCards
   * @covers TheSportsDb\Entity\Event::getHomeLineupGoalkeeper
   * @covers TheSportsDb\Entity\Event::getHomeLineupDefense
   * @covers TheSportsDb\Entity\Event::getHomeLineupMidfield
   * @covers TheSportsDb\Entity\Event::getHomeLineupForward
   * @covers TheSportsDb\Entity\Event::getHomeLineupSubstitutes
   * @covers TheSportsDb\Entity\Event::getHomeFormation
   * @covers TheSportsDb\Entity\Event::getAwayRedCards
   * @covers TheSportsDb\Entity\Event::getAwayYellowCards
   * @covers TheSportsDb\Entity\Event::getAwayGoalDetails
   * @covers TheSportsDb\Entity\Event::getAwayLineupGoalkeeper
   * @covers TheSportsDb\Entity\Event::getAwayLineupDefense
   * @covers TheSportsDb\Entity\Event::getAwayLineupMidfield
   * @covers TheSportsDb\Entity\Event::getAwayLineupForward
   * @covers TheSportsDb\Entity\Event::getAwayLineupSubstitutes
   * @covers TheSportsDb\Entity\Event::getAwayFormation
   * @covers TheSportsDb\Entity\Event::getHomeShots
   * @covers TheSportsDb\Entity\Event::getAwayShots
   * @covers TheSportsDb\Entity\Event::getDate
   * @covers TheSportsDb\Entity\Event::getTvStation
   * @covers TheSportsDb\Entity\Event::getHomeTeam
   * @covers TheSportsDb\Entity\Event::getAwayTeam
   * @covers TheSportsDb\Entity\Event::getResult
   * @covers TheSportsDb\Entity\Event::getCircuit
   * @covers TheSportsDb\Entity\Event::getCountry
   * @covers TheSportsDb\Entity\Event::getCity
   * @covers TheSportsDb\Entity\Event::getPoster
   * @covers TheSportsDb\Entity\Event::getThumb
   * @covers TheSportsDb\Entity\Event::getBanner
   * @covers TheSportsDb\Entity\Event::getMap
   * @covers TheSportsDb\Entity\Event::getLocked
   */
  public function testGetters() {
    parent::testGetters();
  }

  /**
   * @covers TheSportsDb\Entity\Event::transformLeague
   * @todo   Implement testTransformLeague().
   */
  public function testTransformLeague() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Event::transformSeason
   * @todo   Implement testTransformSeason().
   */
  public function testTransformSeason() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Event::transformHomeTeam
   * @todo   Implement testTransformHomeTeam().
   */
  public function testTransformHomeTeam() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Event::transformAwayTeam
   * @todo   Implement testTransformAwayTeam().
   */
  public function testTransformAwayTeam() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }



}
