<?php

namespace TheSportsDb\Test\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 11:40:08.
 */
class PlayerTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Player';

  /**
   * @covers TheSportsDb\Entity\Player::getId
   * @covers TheSportsDb\Entity\Player::getTeam
   * @covers TheSportsDb\Entity\Player::getNationality
   * @covers TheSportsDb\Entity\Player::getName
   * @covers TheSportsDb\Entity\Player::getSport
   * @covers TheSportsDb\Entity\Player::getBirthDay
   * @covers TheSportsDb\Entity\Player::getDateSigned
   * @covers TheSportsDb\Entity\Player::getSigning
   * @covers TheSportsDb\Entity\Player::getWage
   * @covers TheSportsDb\Entity\Player::getBirthLocation
   * @covers TheSportsDb\Entity\Player::getDescription
   * @covers TheSportsDb\Entity\Player::getGender
   * @covers TheSportsDb\Entity\Player::getPosition
   * @covers TheSportsDb\Entity\Player::getFacebook
   * @covers TheSportsDb\Entity\Player::getWebsite
   * @covers TheSportsDb\Entity\Player::getTwitter
   * @covers TheSportsDb\Entity\Player::getInstagram
   * @covers TheSportsDb\Entity\Player::getYoutube
   * @covers TheSportsDb\Entity\Player::getHeight
   * @covers TheSportsDb\Entity\Player::getWeight
   * @covers TheSportsDb\Entity\Player::getThumb
   * @covers TheSportsDb\Entity\Player::getCutout
   * @covers TheSportsDb\Entity\Player::getLocked
   */
  public function testGetters() {
    parent::testGetters();
  }

  /**
   * @covers TheSportsDb\Entity\Player::transformTeam
   * @todo   Implement testTransformTeam().
   */
  public function testTransformTeam() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Player::transformSport
   * @todo   Implement testTransformSport().
   */
  public function testTransformSport() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Player::initPropertyMapDefinition()
   */
  public function testInitPropertyMapDefinition() {
    parent::testInitPropertyMapDefinition();
  }

}
