<?php

namespace TheSportsDb\Test\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 11:37:00.
 */
class SeasonTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Season';

  /**
   * @covers TheSportsDb\Entity\Season::getId
   * @covers TheSportsDb\Entity\Season::getName
   * @covers TheSportsDb\Entity\Season::getLeague
   * @covers TheSportsDb\Entity\Season::getEvents
   */
  public function testGetters() {
    parent::testGetters();
  }

  /**
   * @covers TheSportsDb\Entity\Season::transformLeague
   * @todo   Implement testTransformLeague().
   */
  public function testTransformLeague() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Season::transformEvents
   * @todo   Implement testTransformEvents().
   */
  public function testTransformEvents() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Season::transformId
   * @todo   Implement testTransformId().
   */
  public function testTransformId() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TheSportsDb\Entity\Season::reverseId
   * @todo   Implement testReverseId().
   */
  public function testReverseId() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
