<?php

namespace TheSportsDb\Test\Entity;

use TheSportsDb\Entity\League;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 11:34:01.
 */
class SportTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Sport';

  protected function initTestValues() {
    parent::initTestValues();
    $this->testValues->leagues = array(
      $this->getTestValue() => $this->getTestValue(),
    );
  }

  /**
   * @covers TheSportsDb\Entity\Sport::getId
   * @covers TheSportsDb\Entity\Sport::getName
   * @covers TheSportsDb\Entity\Sport::getLeagues
   */
  public function testGetters() {
    parent::testGetters();
  }

  /**
   * @covers TheSportsDb\Entity\Sport::addLeague
   */
  public function testAddLeague() {
    $league = new League((object) array('id' => 1));
    $this->entity->addLeague($league);
    $leagues = $this->entity->getLeagues();
    $this->assertTrue(isset($leagues[1]));
    $this->assertEquals($league, $leagues[1]);
  }
  /**
   * @covers TheSportsDb\Entity\Sport::transformLeagues
   */

}
