<?php

namespace TheSportsDb\Test\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 11:34:01.
 */
class SportTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Sport';

  /**
   * @covers TheSportsDb\Entity\Sport::getId
   * @covers TheSportsDb\Entity\Sport::getName
   * @covers TheSportsDb\Entity\Sport::getLeagues
   */
  public function testGetters() {
    parent::testGetters();
  }

  /**
   * @covers TheSportsDb\Entity\Sport::addLeague
   * @covers TheSportsDb\Entity\Sport::transformLeagues
   */

}
