<?php

namespace TheSportsDb\Test\Entity\Proxy;

use TheSportsDb\Test\Entity\AbstractEntityTest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 12:27:32.
 */
class EventProxyTest extends AbstractEntityTest {

   protected $entityClass = '\\TheSportsDb\\Entity\\Proxy\\EventProxy';

  /**
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getId
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getName
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getLeague
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getFilename
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getSeason
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getDescription
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeScore
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getRound
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayScore
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getSpecators
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeGoalDetails
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeRedCards
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeYellowCards
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeLineupGoalkeeper
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeLineupDefense
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeLineupMidfield
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeLineupForward
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeLineupSubstitues
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeFormation
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayRedCards
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayYellowCards
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayGoalDetails
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayLineupGoalkeeper
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayLineupDefense
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayLineupMidfield
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayLineupForward
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayLineupSubstitutes
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayFormation
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeShots
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayShots
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getDate
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getTvStation
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getHomeTeam
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getAwayTeam
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getResult
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getCircuit
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getCountry
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getCity
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getPoster
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getThumb
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getBanner
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getMap
   * @covers TheSportsDb\Entity\Proxy\EventProxy::getLocked
   */
  public function testGetters() {
    parent::testGetters();
  }


}
