<?php

use TheSportsDb\Test\Entity\AbstractEntityTest;

namespace TheSportsDb\Test\Entity\Proxy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 12:27:22.
 */
class LeagueProxyTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Proxy\\LeagueProxy';
  /**
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getId
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getName
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getSport
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getAlternateName
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getFormedYear
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getDateFirstEvent
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getGender
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getCountry
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getWebsite
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getFacebook
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getTwitter
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getYoutube
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getRss
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getDescription
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getBanner
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getBadge
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getLogo
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getPoster
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getTrophy
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getNaming
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getLocked
   * @covers TheSportsDb\Entity\Proxy\LeagueProxy::getSeasons
   */
  public function testGetters() {
    parent::testGetters();
  }

}
