<?php

namespace TheSportsDb\Test\Entity\Proxy;

use TheSportsDb\Test\Entity\AbstractEntityTest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 12:27:14.
 */
class PlayerProxyTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Proxy\\PlayerProxy';

  /**
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getId
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getTeam
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getNationality
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getName
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getSport
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getBirthDay
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getDateSigned
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getSigning
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getWage
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getBirthLocation
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getDescription
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getGender
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getPosition
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getFacebook
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getWebsite
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getTwitter
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getInstagram
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getYoutube
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getHeight
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getWeight
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getThumb
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getCutout
   * @covers TheSportsDb\Entity\Proxy\PlayerProxy::getLocked
   */
  public function testGetters() {
    parent::testGetters();
  }

}
