<?php

namespace TheSportsDb\Test\Entity\Proxy;

use TheSportsDb\Test\Entity\AbstractEntityTest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 12:23:58.
 */
class SeasonProxyTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Proxy\\SeasonProxy';

  /**
   * @covers TheSportsDb\Entity\Proxy\SeasonProxy::getId
   * @covers TheSportsDb\Entity\Proxy\SeasonProxy::getName
   * @covers TheSportsDb\Entity\Proxy\SeasonProxy::getLeague
   * @covers TheSportsDb\Entity\Proxy\SeasonProxy::getEvents
   */
  public function testGetters() {
    parent::testGetters();
  }


}
