<?php

namespace TheSportsDb\Test\Entity\Proxy;

use TheSportsDb\Entity\League;
use TheSportsDb\Test\Entity\AbstractEntityTest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 12:22:13.
 */
class SportProxyTest extends AbstractEntityTest {

  protected $entityClass = '\\TheSportsDb\\Entity\\Proxy\\SportProxy';

  protected function initTestValues() {
    parent::initTestValues();
    $this->testValues->leagues = array(
      $this->getTestValue() => $this->getTestValue(),
    );
  }

  /**
   * @covers TheSportsDb\Entity\Proxy\SportProxy::getId
   * @covers TheSportsDb\Entity\Proxy\SportProxy::getName
   * @covers TheSportsDb\Entity\Proxy\SportProxy::getLeagues
   */
  public function testGetters() {
    parent::testGetters();
  }

  /**
   * @covers TheSportsDb\Entity\Proxy\SportProxy::addLeague
   */
  public function testAddLeague() {
    $league = new League((object) array('id' => 1));
    $this->entity->addLeague($league);
    $leagues = $this->entity->getLeagues();
    $this->assertTrue(isset($leagues[1]));
    $this->assertEquals($league, $leagues[1]);
  }

}
