<?php

namespace TheSportsDb\Test\Entity\Proxy;

use TheSportsDb\Test\Entity\AbstractEntityTest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-14 at 12:14:58.
 */
class TeamProxyTest extends AbstractEntityTest {
  protected $entityClass = '\\TheSportsDb\\Entity\\Proxy\\TeamProxy';
  /**
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getId
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getName
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getTeamShort
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getAlternateName
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getFormedYear
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getSport
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getLeague
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getDivision
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getManager
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getStadium
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getKeywords
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getRss
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getStadiumThumb
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getStadiumDescription
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getStadiumLocation
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getStadiumCapacity
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getWebsite
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getFacebook
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getTwitter
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getInstagram
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getDescription
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getGender
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getCountry
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getBadge
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getJersey
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getLogo
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getBanner
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getYoutube
   * @covers TheSportsDb\Entity\Proxy\TeamProxy::getLocked
   */
  public function testGetters() {
   parent::testGetters();
  }

}
