<?php

namespace TheSportsDb\Test\Http;

use GuzzleHttp\Client;
use TheSportsDb\Http\TheSportsDbClient;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-06 at 12:31:28.
 */
class TheSportsDbClientTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var TheSportsDbClient
   */
  protected $client;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->client = new TheSportsDbClient(1, new Client());
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    $this->client = NULL;
  }

  /**
   * @covers TheSportsDb\Http\TheSportsDbClient::doRequest
   */
  public function testDoRequest() {
    $result = $this->client->doRequest('all_leagues.php');
    $this->assertTrue(is_object($result));
    $this->assertTrue(is_array($result->leagues));

    $this->expectException(\Exception::class);
    $this->expectExceptionMessage('Request to http://thesportsdb.com/api/v1/json/1/fakeendpoint.php failed: 404 Not Found.');
    $this->client->doRequest('fakeendpoint.php');
  }

}
