<?php

namespace TheSportsDb\Test\PropertyMapper\Transformer;

use TheSportsDb\PropertyMapper\Transformer\Callback;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-15 at 09:29:22.
 */
class CallbackTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Callback
   */
  protected $callback;

  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = $this->getMockBuilder('\\stdClass')->setMethods(array('transform', 'reverse'))->getMock();
    $this->callback = new Callback(array($this->object, 'transform'), array($this->object, 'reverse'));
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    $this->object = NULL;
    $this->callback = NULL;
  }

  /**
   * @covers TheSportsDb\PropertyMapper\Transformer\Callback::transform
   */
  public function testTransform() {
    $this->object->expects($this->once())->method('transform')->with('testValue', 'testContext');
    $this->callback->transform('testValue', 'testContext');
  }

  /**
   * @covers TheSportsDb\PropertyMapper\Transformer\Callback::reverse
   */
  public function testReverse() {
    $this->object->expects($this->once())->method('reverse')->with('testValue', 'testContext');
    $this->callback->reverse('testValue', 'testContext');
  }

}
